=== daniromero22/ejerciciosLmsgi_dani/examen03.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="movilesYFundas" type="tipomovil"/>

  <xs:complexType name="tipomovil" mixed="true">
    <xs:sequence>
      <xs:element name="telefono" type="masAtributos" maxOccurs="unbounded"/>
      <xs:element name="funda" type="tipoParte" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipoParte">
    <xs:all>
      <xs:element name="estilo" type="tipoNombreDeParte"/>
      <xs:element name="escenario" minOccurs="0" type="tipoAtributoNombre"/>
      <xs:element name="pais" minOccurs="0" type="tipoAtributoNombre"/>
      <xs:element name="puntuacion" type="tipoPuntuación"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="tipoAtributoNombre">
    <xs:attribute name="nombre" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="masAtributos">
    <xs:complexContent>
      <xs:extension base="tipoAtributoNombre">
        <xs:attribute name="relacionCon" type="xs:string"/>
        <xs:attribute name="enemigo" type="tipoAtributoEnemigoPorPattern"/>
        <xs:attribute name="rol" type="xs:string"/>
          </xs:extension>
    </xs:complexContent>
  </xs:complexType>  


  <xs:complexType name="tipoPuntuación">
    <xs:sequence>
      <xs:element name="valoracion" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="longitudMinimaUnCaracter">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoAtributoEnemigo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Johnny"/>
      <xs:enumeration value="Daniel"/>      
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoAtributoEnemigoPorPattern">
    <xs:restriction base="xs:string">
      <xs:pattern value="((Johnny)|(Daniel)|( )){1,}"/>      
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoNombreDeParte">
    <xs:restriction base="xs:string">
      <xs:pattern value="[I]{1,3}[ - ]?.*"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== daniromero22/ejerciciosLmsgi_dani/examen03.xml
<?xml version="1.0" encoding="UTF-8"?>
<movilesYFundas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="examen03.xsd">
	Karate Kid
	<telefono nombre="Alice" relacionCon="Daniel Johnny" />
	<telefono nombre="Daniel" enemigo="Johnny" />
	<telefono nombre="Johnny" enemigo="Daniel Johnny Daniel Johnny Daniel " />
	<telefono nombre="Miyagi" rol="sensei" />
	<funda>
		<estilo>I - Rosa</estilo>
		<escenario nombre="California" />
		<puntuacion>
			<valoracion>Una web que le da un 9</valoracion>
			<valoracion>Una web que le da un 10</valoracion>
		</puntuacion>
	</funda>
	<funda>
		<estilo>III - Azul</estilo>
		<pais nombre="Japon" />
		<puntuacion>
			<valoracion>Una web que le da un 9</valoracion>
			<valoracion>Una web que le da un 10</valoracion>
		</puntuacion>
	</funda>
</movilesYFundas>
