=== daniromero22/ejerciciosLmsgi_dani/examen01.dtd
<!ELEMENT cocteleria (cocteles, combos)>
<!ELEMENT cocteles (coctel+)>
<!ELEMENT combos (combo*)>
<!ELEMENT coctel (nombre, precio, alcohol?, ingredientes, (disponible | agotado))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ingredientes EMPTY>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT alcohol EMPTY>
<!ELEMENT disponible EMPTY>
<!ELEMENT agotado EMPTY>
<!ELEMENT combo (#PCDATA)>
<!ELEMENT tipococtel ANY>
<!ATTLIST direccion cocteleria CDATA #IMPLIED
                    nombre CDATA #REQUIRED
                    telefono CDATA #FIXED "957349618">
<!ATTLIST ingredientes ID #REQUIRED
                    contenidoPrincipal (ron | ginebra | vodka)>

<!ENTITY % atributoCoste "coste DATA #IMPLIED">
<!ATTLIST precio %atributoCoste;>
<!ATTLIST combo %atributoCoste;>
<!ENTITY fuerte "% elevado">

=== daniromero22/ejerciciosLmsgi_dani/examen01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cocteleria SYSTEM "examen01.dtd">
<cocteleria direccion="calle arÃ©balo" nombre="coctelitos" telefono="957349618">
   <cocteles>
      <coctel codigo="marg" contenidoPrincipal="vodka">
         <nombre/>
         <precio coste="6" />
         <alcohol/>
         <ingredientes/>
         <disponible/>
      </coctel>
    
   </cocteles>
   <ofertas>
      <combo coste="6"/>

   </ofertas> 
</cocteleria>
