=== daniromero22/ejerciciosLmsgi_dani/examen02.dtd
<!ELEMENT juego (campeones, modos)>
<!ELEMENT campeones (campeon+)>
<!ELEMENT modos (modo*)>
<!ELEMENT campeon (rol, dificultad?, (nuevo | antiguo))>
<!ELEMENT rol (#PCDATA | lugarDelMapa)*>
<!ELEMENT lugarDelMapa (#PCDATA)>
<!ELEMENT dificultad EMPTY>
<!ELEMENT nuevo EMPTY>
<!ELEMENT antiguo EMPTY>
<!ATTLIST dificultad nivel (baja | media | alta) "media">
<!ATTLIST campeon nombre (ahri | atrox | ekko | xayah | brand ) "ahri"
                    tipo CDATA #IMPLIED
                    codigo ID #REQUIRED
                    lugarDeCombate CDATA #FIXED "grieta del invocador">
<!ENTITY % atributoNombre "nombre CDATA #REQUIRED">
<!ATTLIST juego losMejoresPersonajes IDREFS #REQUIRED>
<!ELEMENT modo (#PCDATA)>
<!ATTLIST modo masDestacado IDREF #REQUIRED
                %atributoNombre;>

=== daniromero22/ejerciciosLmsgi_dani/examen02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE juego SYSTEM "examen02.dtd">
<juego losMejoresPersonajes="ahr xay">
   <campeones>
      <campeon nombre="ahri" tipo="mago" codigo="ahr" lugarDeCombate="grieta del invocador">
         <rol>
            Mid
            <lugarDelMapa> centro </lugarDelMapa>
         </rol> 
         <dificultad nivel="baja"/>
         <antiguo />
      </campeon>
      <campeon nombre="atrox" tipo="tanque" codigo="atr" lugarDeCombate="grieta del invocador">
         <rol>
            Top
            <lugarDelMapa>Superior</lugarDelMapa>
         </rol>
         <dificultad nivel="baja"/>
         <antiguo />
      </campeon>
      <campeon nombre="ekko" tipo="mago" codigo="ekk" lugarDeCombate="grieta del invocador">
         <rol/>
         <dificultad nivel="baja"/>
         <antiguo />
      </campeon>
      <campeon nombre="xayah" tipo="mago" codigo="xay" lugarDeCombate="grieta del invocador">
         <rol/>
         <dificultad nivel="baja"/>
         <antiguo />
      </campeon>
   </campeones>

   <modos>
      <modo nombre="aram" masDestacado="xay"></modo>
      <modo nombre="teamTactics" masDestacado="ahr"></modo>
      <modo nombre="grietadelinvocador" masDestacado="atr"></modo>
   </modos>
</juego>
