=== daniromero22/ejerciciosLmsgi_dani/ExamenLmsgi_RomeroRanchalDaniel/EXAMEN17.dtd
<!ELEMENT receta (medicamentos, pacientes, medico)*>
<!ELEMENT medicamentos (medicamento)*>
<!ELEMENT medicos (medico)>
<!ELEMENT pacientes (paciente+)>
<!ELEMENT paciente (trabajo, recetado?, (joven | mayor))>
<!ELEMENT trabajo (#PCDATA | peligro)*>
<!ELEMENT peligro ANY>
<!ELEMENT recetado EMPTY>
<!ELEMENT joven EMPTY>
<!ELEMENT mayor EMPTY>
<!ATTLIST recetado medicamento IDREF #REQUIRED>
<!ATTLIST paciente nombre (dani | alex | rafa | maria | jose ) "dani"
                    edad CDATA #IMPLIED
                    codigo ID #REQUIRED
                    procedencia CDATA #FIXED "lucena">
<!ENTITY % atributoNombre "nombre CDATA #REQUIRED">
<!ATTLIST receta elMedicamentoPorExcelencia IDREFS #REQUIRED>
<!ELEMENT medico (#PCDATA)>
<!ATTLIST medico medicaA IDREF #REQUIRED
                %atributoNombre;>
<!ENTITY porDefecto "Paracetamol">
<!ELEMENT medicamento EMPTY>
<!ATTLIST medicamento %atributoNombre;
                        codigo ID #REQUIRED>

=== daniromero22/ejerciciosLmsgi_dani/ExamenLmsgi_RomeroRanchalDaniel/EXAMEN17.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE receta SYSTEM "EXAMEN17.dtd">
<receta elMedicamentoPorExcelencia="par hib">
   
   <medicamentos>
      <medicamento nombre="paracetamol" codigo="par"></medicamento>
      <medicamento nombre="hibuprofeno" codigo="hib"></medicamento>
      <medicamento nombre="algidol" codigo="alg"></medicamento>
   </medicamentos>

   <pacientes>
      <paciente nombre="dani" edad="21" codigo="dan" procedencia="lucena">
         <trabajo>
            Camarero
            <peligro> en algunas circustancias </peligro>
         </trabajo> 
         <recetado medicamento="alg"/>
         <joven />
      </paciente>
      <paciente nombre="maria" edad="55" codigo="mar" procedencia="lucena">
         <trabajo>
            carpintera
            <peligro> carga de objetos pesados </peligro>
         </trabajo> 
         <recetado medicamento="par"/>
         <mayor />
      </paciente>
   </pacientes>

   <medico medicaA="dan" nombre="julio"></medico>
</receta>
